variable "aws_region" {}
variable "target_group_arn" {}
variable "asg_arn" {}
variable "container_name" {}
variable "container_port" {}
variable "container_image" {}
variable "name" {}
variable "env" {}
variable "application_id" {}
variable "service_desired_count" {}
variable "cost_centre" {}
variable "owner" {}
variable "alb_dns_name" {}
variable "host_port" {}
